name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'  # cache pip dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Perform linting
      run: make lint
